DELETE FROM train;
DELETE FROM station;
DELETE FROM coach;
DELETE FROM engine;
DELETE FROM date;
DELETE FROM employee;
DELETE FROM berth;
-- DELETE FROM platform;
DELETE FROM tr_comp;
DELETE FROM tr_route;
DELETE FROM booking;
DELETE FROM tr_emp;
DELETE FROM st_emp;
DELETE FROM pf_avbl;

INSERT into station values('VSKP', null, 'Visakhapatnam', 8);
INSERT into station values('PAP', null, 'Pithapuram', 2);
INSERT into station values('SLO', null, 'Samalkot', 4);
INSERT into station values('RJY', null, 'Rajamundry', 6);
INSERT into station values('TNKU', null, 'Tanuku', 2);
INSERT into station values('BVRT', null, 'Bhimavaram Town', 4);
INSERT into station values('AKVD', null, 'Akividu', 3);
INSERT into station values('KKLR', null, 'Kaikolur',2 );
INSERT into station values('GDV', null, 'Gudivada', 3);
INSERT into station values('BZA', null, 'Vijayawada', 7);
INSERT into station values('KZJ', null, 'Kazipet', 2);
INSERT into station values('MLY', null, 'Maula Ali', 2);
INSERT into station values('SC', null, 'Secunderabad', 10);
INSERT into station values('LPI', null, 'Lingampally', 5);
INSERT into station values('VKB', null, 'Vikarabad', 2);
INSERT into station values('TDU', null, 'Tandur', 2);
INSERT into station values('WADI', null, 'Wadi', 3);
INSERT into station values('KLBG', null, 'Kalaburagi', 2);
INSERT into station values('SUR', null, 'Solapur', 4);
INSERT into station values('PUNE', null, 'Pune', 6);
INSERT into station values('LTT', 'Lokamanya Tilak Terminus', 'Mumbai', 10);

INSERT into train values(18519, ' LTT SPL', '', 'LTT', timestamp '2022-03-09 11:00:00', timestamp '2022-03-10 11:00:00', 'special');
INSERT into train values(11020, ' LTT S F', '', 'LTT', timestamp '2022-03-09 11:00:00', timestamp '2022-03-10 11:00:00', 'weekly');
